package com.SheldonSandbekkhaug.Peace;

public enum EventType {
	JOIN, START, SETUP_DONE, NEXT_TURN, LEAVE, STOP,
	TO_MARKET, FROM_MARKET,
	ADD_PLAYER, PLAYER_UPDATE,
	MOVE, ATTACK,
	UPDATE_ENTITY, REMOVE_ENTITY
}
