package com.SheldonSandbekkhaug.Peace;

public class Structure extends PeaceEntity {
	// NOTE: Must change clone() when adding/removing properties
	private int income; // Income per turn generated by this Structure
	
	public Structure()
	{
		super();
		income = 0;
	}
	
	public Structure clone()
	{
		Structure s = new Structure();
		s.cloneHelper(this);
		s.setIncome(income);
		
		return s;
	}

	public int getIncome() {
		return income;
	}

	public void setIncome(int income) {
		this.income = income;
	}
}
